# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# Uncomment this line if you're using Swift
# use_frameworks!
inhibit_all_warnings!

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'AgoraChat-Swift' do
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'Agora_Chat_iOS'
    pod 'chat-uikit'
    pod 'AgoraChatCallKit'
    pod 'SnapKit'
    pod 'SwiftLint'
    pod 'Kingfisher'
    pod 'MJExtension'
    pod 'Bugly'
end
